### ISSUE TITLE
技术选型请教？

### ISSUE THREAD

**Issue by rts-gordon** [pipe-fun/pipe#1]
看了pipe的实现，很不错，各种技术都尝试用过了。请问如果一个CRM的web网站的技术选型，你推荐哪种？谢谢。
web: Rocket or Actix？
orm: Rocket自带Diesel， or sqlx?

**Comment by Spxg** [comment]
> 看了pipe的实现，很不错，各种技术都尝试用过了。请问如果一个CRM的web网站的技术选型，你推荐哪种？谢谢。
> web: Rocket or Actix？
> orm: Rocket自带Diesel， or sqlx?

Rocket比较好上手，日志详细，但是现阶段不支持异步，所以同时也不支持异步的orm，比如sqlx

Actix支持异步，可以用异步的orm，性能较好，但相比rocket不好上手

orm我个人建议使用sqlx，所以数据库接口那一部分可以使用actix

**Comment by rts-gordon** [comment]
Thanks
